### ISSUE TITLE
Not bootable

### ISSUE THREAD

**Issue by tuvalutorture** [turrnut/beacon#2]
its an OS but i can't boot into it???

**Comment by tuvalutorture** [comment]
maybe im just dumb but i cant boot into it

**Comment by turrnut** [comment]
@skyrizzle Did you enable Legacy Support? It needs legacy support to boot.

**Comment by tuvalutorture** [comment]
oh lol

**Comment by tuvalutorture** [comment]
in all reality i just didnt know how to compile and run it back then lmao
